/**
 * Auth Debug Page - Temporary helper for troubleshooting auth configuration
 * Access at /auth-debug
 * 
 * Shows:
 * - Current auth configuration
 * - Session state
 * - URL parameters
 * - Computed redirect URLs
 */

import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { getAuthBaseUrl, getEmailRedirectUrl, getPasswordResetRedirectUrl, getMagicLinkRedirectUrl, logAuthConfig } from "@/utils/authRedirects";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, Copy, CheckCircle, XCircle, AlertTriangle } from "lucide-react";
import { toast } from "sonner";

export default function AuthDebug() {
  const navigate = useNavigate();
  const [session, setSession] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState<string | null>(null);

  useEffect(() => {
    logAuthConfig();
    
    supabase.auth.getSession().then(({ data }) => {
      setSession(data.session);
      setLoading(false);
    });
  }, []);

  const copyToClipboard = async (text: string, label: string) => {
    await navigator.clipboard.writeText(text);
    setCopied(label);
    toast.success(`Copied ${label}`);
    setTimeout(() => setCopied(null), 2000);
  };

  const config = {
    baseUrl: getAuthBaseUrl(),
    emailRedirect: getEmailRedirectUrl(),
    passwordReset: getPasswordResetRedirectUrl(),
    magicLink: getMagicLinkRedirectUrl(),
    currentOrigin: window.location.origin,
    currentHref: window.location.href,
    currentPathname: window.location.pathname,
    currentHash: window.location.hash,
    currentSearch: window.location.search,
  };

  const requiredRedirectUrls = [
    'https://monarchpropertymmgt.com',
    'https://monarchpropertymmgt.com/*',
    'https://monarchpropertymmgt.com/auth/callback',
    'https://monarchpropertymmgt.com/auth/verify',
    'https://monarchpropertymmgt.com/login-bridge',
  ];

  return (
    <div className="min-h-screen bg-background p-6">
      <div className="max-w-4xl mx-auto space-y-6">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" onClick={() => navigate(-1)}>
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div>
            <h1 className="text-2xl font-bold text-foreground">Auth Debug</h1>
            <p className="text-sm text-muted-foreground">Troubleshoot authentication configuration</p>
          </div>
        </div>

        {/* Session Status */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              Session Status
              {loading ? (
                <Badge variant="secondary">Loading...</Badge>
              ) : session ? (
                <Badge className="bg-green-500/20 text-green-700">Active</Badge>
              ) : (
                <Badge variant="destructive">Not authenticated</Badge>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {session ? (
              <div className="space-y-2 text-sm">
                <p><strong>User ID:</strong> {session.user?.id}</p>
                <p><strong>Email:</strong> {session.user?.email}</p>
                <p><strong>Role:</strong> {session.user?.role || 'N/A'}</p>
                <p><strong>Expires:</strong> {new Date(session.expires_at * 1000).toLocaleString()}</p>
              </div>
            ) : (
              <p className="text-sm text-muted-foreground">No active session</p>
            )}
          </CardContent>
        </Card>

        {/* Current URL Info */}
        <Card>
          <CardHeader>
            <CardTitle>Current URL</CardTitle>
            <CardDescription>Information about the current page URL</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <InfoRow label="Origin" value={config.currentOrigin} onCopy={copyToClipboard} copied={copied} />
            <InfoRow label="Pathname" value={config.currentPathname} onCopy={copyToClipboard} copied={copied} />
            <InfoRow label="Search" value={config.currentSearch || '(none)'} onCopy={copyToClipboard} copied={copied} />
            <InfoRow label="Hash" value={config.currentHash || '(none)'} onCopy={copyToClipboard} copied={copied} />
          </CardContent>
        </Card>

        {/* Computed Redirect URLs */}
        <Card>
          <CardHeader>
            <CardTitle>Computed Redirect URLs</CardTitle>
            <CardDescription>These URLs are generated by the application for auth flows</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <InfoRow label="Base URL" value={config.baseUrl} onCopy={copyToClipboard} copied={copied} />
            <InfoRow label="Email Redirect" value={config.emailRedirect} onCopy={copyToClipboard} copied={copied} />
            <InfoRow label="Password Reset" value={config.passwordReset} onCopy={copyToClipboard} copied={copied} />
            <InfoRow label="Magic Link" value={config.magicLink} onCopy={copyToClipboard} copied={copied} />
          </CardContent>
        </Card>

        {/* Required Supabase Config */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-amber-500" />
              Required Supabase Dashboard Config
            </CardTitle>
            <CardDescription>
              These URLs must be added in Supabase → Authentication → URL Configuration
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <p className="text-sm font-medium mb-2">Site URL:</p>
              <code className="block bg-muted p-2 rounded text-sm">https://monarchpropertymmgt.com</code>
            </div>
            <div>
              <p className="text-sm font-medium mb-2">Redirect URLs (add all):</p>
              <div className="space-y-1">
                {requiredRedirectUrls.map((url) => (
                  <div key={url} className="flex items-center gap-2">
                    <code className="flex-1 bg-muted p-2 rounded text-sm">{url}</code>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8"
                      onClick={() => copyToClipboard(url, url)}
                    >
                      {copied === url ? <CheckCircle className="h-4 w-4 text-green-500" /> : <Copy className="h-4 w-4" />}
                    </Button>
                  </div>
                ))}
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Email Template Check */}
        <Card>
          <CardHeader>
            <CardTitle>Email Template Requirements</CardTitle>
            <CardDescription>Verify these settings in Supabase → Authentication → Email Templates</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="p-3 bg-amber-500/10 border border-amber-500/20 rounded-lg">
              <p className="text-sm font-medium text-amber-700 dark:text-amber-400 mb-2">
                Confirmation URL format should be:
              </p>
              <code className="block bg-background p-2 rounded text-xs break-all">
                {'{{ .SiteURL }}/login-bridge#access_token={{ .Token }}&type={{ .Type }}&redirect_to={{ .RedirectTo }}'}
              </code>
            </div>
            <div className="text-sm text-muted-foreground">
              <p className="font-medium">Common issues:</p>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li>Missing <code>https://</code> in Site URL causes malformed redirects</li>
                <li>Using <code>{'{{ .ConfirmationURL }}'}</code> may include wrong domain</li>
                <li>Ensure Site URL matches your production domain exactly</li>
              </ul>
            </div>
          </CardContent>
        </Card>

        {/* Debug Actions */}
        <Card>
          <CardHeader>
            <CardTitle>Debug Actions</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-wrap gap-3">
            <Button
              variant="outline"
              onClick={() => {
                localStorage.setItem('DEBUG_AUTH', '1');
                toast.success('Auth debug logging enabled');
              }}
            >
              Enable Debug Logging
            </Button>
            <Button
              variant="outline"
              onClick={() => {
                localStorage.removeItem('DEBUG_AUTH');
                toast.success('Auth debug logging disabled');
              }}
            >
              Disable Debug Logging
            </Button>
            <Button
              variant="outline"
              onClick={async () => {
                await supabase.auth.signOut();
                toast.success('Signed out');
                setSession(null);
              }}
            >
              Force Sign Out
            </Button>
            <Button
              variant="outline"
              onClick={() => navigate('/auth')}
            >
              Go to Auth Page
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function InfoRow({ 
  label, 
  value, 
  onCopy, 
  copied 
}: { 
  label: string; 
  value: string; 
  onCopy: (text: string, label: string) => void;
  copied: string | null;
}) {
  return (
    <div className="flex items-center gap-2">
      <span className="text-sm font-medium w-32 shrink-0">{label}:</span>
      <code className="flex-1 bg-muted p-2 rounded text-xs break-all">{value}</code>
      <Button
        variant="ghost"
        size="icon"
        className="h-8 w-8 shrink-0"
        onClick={() => onCopy(value, label)}
      >
        {copied === label ? <CheckCircle className="h-4 w-4 text-green-500" /> : <Copy className="h-4 w-4" />}
      </Button>
    </div>
  );
}
