/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as AuthDebugRouteImport } from './routes/auth-debug'
import { Route as AuthTestRouteImport } from './routes/auth-test'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as JoinAsVendorRouteImport } from './routes/join-as-vendor'
import { Route as LoginBridgeRouteImport } from './routes/login-bridge'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RequestQuoteRouteImport } from './routes/request-quote'
import { Route as RfqSystemRouteImport } from './routes/rfq-system'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThemePreviewRouteImport } from './routes/theme-preview'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminBidsRouteImport } from './routes/admin.bids'
import { Route as AdminComponentPlaygroundRouteImport } from './routes/admin.component-playground'
import { Route as AdminControlSuiteRouteImport } from './routes/admin.control-suite'
import { Route as AdminDesignTokensRouteImport } from './routes/admin.design-tokens'
import { Route as AdminEmdRouteImport } from './routes/admin.emd'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminOperationsRouteImport } from './routes/admin.operations'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminRfqAccessRouteImport } from './routes/admin.rfq-access'
import { Route as AdminSalesiqRouteImport } from './routes/admin.salesiq'
import { Route as AdminSecurityTestingRouteImport } from './routes/admin.security-testing'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminTestingRouteImport } from './routes/admin.testing'
import { Route as AdminWorkOrdersRouteImport } from './routes/admin.work-orders'
import { Route as ApartmentsIdRouteImport } from './routes/apartments.$id'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as BlogHowToChoosePropertyManagementCompanyRouteImport } from './routes/blog.how-to-choose-property-management-company'
import { Route as BookPropertyIdRouteImport } from './routes/book.$propertyId'
import { Route as BookingIdRouteImport } from './routes/booking.$id'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardPropertiesRouteImport } from './routes/dashboard.properties'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardTenantsRouteImport } from './routes/dashboard.tenants'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardVendorsRouteImport } from './routes/dashboard.vendors'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as RfqIndexRouteImport } from './routes/rfq.index'
import { Route as RfqIdRouteImport } from './routes/rfq.$id'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesConsultationRouteImport } from './routes/services.consultation'
import { Route as ServicesMaintenanceRouteImport } from './routes/services.maintenance'
import { Route as ServicesPropertyManagementRouteImport } from './routes/services.property-management'
import { Route as VendorOnboardingIndexRouteImport } from './routes/vendor-onboarding.index'
import { Route as VendorOnboardingCapabilitiesRouteImport } from './routes/vendor-onboarding.capabilities'
import { Route as VendorOnboardingCompanyRouteImport } from './routes/vendor-onboarding.company'
import { Route as VendorOnboardingCompleteRouteImport } from './routes/vendor-onboarding.complete'
import { Route as VendorOnboardingComplianceRouteImport } from './routes/vendor-onboarding.compliance'
import { Route as VendorOnboardingProfileRouteImport } from './routes/vendor-onboarding.profile'
import { Route as VendorOnboardingReviewRouteImport } from './routes/vendor-onboarding.review'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as VendorApplicationRouteImport } from './routes/vendor.application'
import { Route as VendorApplicationsRouteImport } from './routes/vendor.applications'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as VendorDocumentsRouteImport } from './routes/vendor.documents'
import { Route as VendorInquiriesRouteImport } from './routes/vendor.inquiries'
import { Route as VendorLeadsRouteImport } from './routes/vendor.leads'
import { Route as VendorMessagesRouteImport } from './routes/vendor.messages'
import { Route as VendorNotificationsRouteImport } from './routes/vendor.notifications'
import { Route as VendorOnboardingRouteImport } from './routes/vendor.onboarding'
import { Route as VendorPaymentsRouteImport } from './routes/vendor.payments'
import { Route as VendorPayoutSettingsRouteImport } from './routes/vendor.payout-settings'
import { Route as VendorPayoutsRouteImport } from './routes/vendor.payouts'
import { Route as VendorProfileRouteImport } from './routes/vendor.profile'
import { Route as VendorProfileShowcaseRouteImport } from './routes/vendor.profile-showcase'
import { Route as VendorReportsRouteImport } from './routes/vendor.reports'
import { Route as VendorSettingsRouteImport } from './routes/vendor.settings'
import { Route as VendorSubscriptionRouteImport } from './routes/vendor.subscription'
import { Route as VendorsVendorIdRouteImport } from './routes/vendors.$vendorId'
import { Route as AdminRfqIndexRouteImport } from './routes/admin.rfq.index'
import { Route as AdminRfqCreateRouteImport } from './routes/admin.rfq.create'
import { Route as AdminRfqCreateDetailedRouteImport } from './routes/admin.rfq.create-detailed'
import { Route as AdminSettingsLabsRouteImport } from './routes/admin.settings.labs'
import { Route as AdminTeamIndexRouteImport } from './routes/admin.team.index'
import { Route as AdminTeamMemberIdRouteImport } from './routes/admin.team.$memberId'
import { Route as AdminVendorsIdRouteImport } from './routes/admin.vendors.$id'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard.projects.index'
import { Route as DashboardProjectsIdRouteImport } from './routes/dashboard.projects.$id'
import { Route as VendorContractsIndexRouteImport } from './routes/vendor.contracts.index'
import { Route as VendorContractsIdRouteImport } from './routes/vendor.contracts.$id'
import { Route as VendorProjectsIndexRouteImport } from './routes/vendor.projects.index'
import { Route as VendorProjectsIdRouteImport } from './routes/vendor.projects.$id'
import { Route as VendorRfqIndexRouteImport } from './routes/vendor.rfq.index'
import { Route as VendorRfqDashboardRouteImport } from './routes/vendor.rfq.dashboard'
import { Route as VendorRfqsIndexRouteImport } from './routes/vendor.rfqs.index'
import { Route as VendorRfqsIdRouteImport } from './routes/vendor.rfqs.$id'
import { Route as AdminRfqIdIndexRouteImport } from './routes/admin.rfq.$id.index'
import { Route as AdminRfqIdEditRouteImport } from './routes/admin.rfq.$id.edit'
import { Route as VendorRfqIdIndexRouteImport } from './routes/vendor.rfq.$id.index'
import { Route as VendorRfqIdBidRouteImport } from './routes/vendor.rfq.$id.bid'
import { Route as VendorRfqIdDetailsRouteImport } from './routes/vendor.rfq.$id.details'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDebugRoute = AuthDebugRouteImport.update({
  id: '/auth-debug',
  path: '/auth-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTestRoute = AuthTestRouteImport.update({
  id: '/auth-test',
  path: '/auth-test',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinAsVendorRoute = JoinAsVendorRouteImport.update({
  id: '/join-as-vendor',
  path: '/join-as-vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginBridgeRoute = LoginBridgeRouteImport.update({
  id: '/login-bridge',
  path: '/login-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqSystemRoute = RfqSystemRouteImport.update({
  id: '/rfq-system',
  path: '/rfq-system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemePreviewRoute = ThemePreviewRouteImport.update({
  id: '/theme-preview',
  path: '/theme-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBidsRoute = AdminBidsRouteImport.update({
  id: '/admin/bids',
  path: '/admin/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComponentPlaygroundRoute =
  AdminComponentPlaygroundRouteImport.update({
    id: '/admin/component-playground',
    path: '/admin/component-playground',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminControlSuiteRoute = AdminControlSuiteRouteImport.update({
  id: '/admin/control-suite',
  path: '/admin/control-suite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDesignTokensRoute = AdminDesignTokensRouteImport.update({
  id: '/admin/design-tokens',
  path: '/admin/design-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmdRoute = AdminEmdRouteImport.update({
  id: '/admin/emd',
  path: '/admin/emd',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/admin/invoices',
  path: '/admin/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/admin/operations',
  path: '/admin/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRfqAccessRoute = AdminRfqAccessRouteImport.update({
  id: '/admin/rfq-access',
  path: '/admin/rfq-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesiqRoute = AdminSalesiqRouteImport.update({
  id: '/admin/salesiq',
  path: '/admin/salesiq',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityTestingRoute = AdminSecurityTestingRouteImport.update({
  id: '/admin/security-testing',
  path: '/admin/security-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestingRoute = AdminTestingRouteImport.update({
  id: '/admin/testing',
  path: '/admin/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkOrdersRoute = AdminWorkOrdersRouteImport.update({
  id: '/admin/work-orders',
  path: '/admin/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsIdRoute = ApartmentsIdRouteImport.update({
  id: '/apartments/$id',
  path: '/apartments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogHowToChoosePropertyManagementCompanyRoute =
  BlogHowToChoosePropertyManagementCompanyRouteImport.update({
    id: '/blog/how-to-choose-property-management-company',
    path: '/blog/how-to-choose-property-management-company',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookPropertyIdRoute = BookPropertyIdRouteImport.update({
  id: '/book/$propertyId',
  path: '/book/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPropertiesRoute = DashboardPropertiesRouteImport.update({
  id: '/dashboard/properties',
  path: '/dashboard/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTenantsRoute = DashboardTenantsRouteImport.update({
  id: '/dashboard/tenants',
  path: '/dashboard/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/dashboard/users',
  path: '/dashboard/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVendorsRoute = DashboardVendorsRouteImport.update({
  id: '/dashboard/vendors',
  path: '/dashboard/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqIndexRoute = RfqIndexRouteImport.update({
  id: '/rfq/',
  path: '/rfq/',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqIdRoute = RfqIdRouteImport.update({
  id: '/rfq/$id',
  path: '/rfq/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesConsultationRoute = ServicesConsultationRouteImport.update({
  id: '/services/consultation',
  path: '/services/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMaintenanceRoute = ServicesMaintenanceRouteImport.update({
  id: '/services/maintenance',
  path: '/services/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPropertyManagementRoute =
  ServicesPropertyManagementRouteImport.update({
    id: '/services/property-management',
    path: '/services/property-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const VendorOnboardingIndexRoute = VendorOnboardingIndexRouteImport.update({
  id: '/vendor-onboarding/',
  path: '/vendor-onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorOnboardingCapabilitiesRoute =
  VendorOnboardingCapabilitiesRouteImport.update({
    id: '/vendor-onboarding/capabilities',
    path: '/vendor-onboarding/capabilities',
    getParentRoute: () => rootRouteImport,
  } as any)
const VendorOnboardingCompanyRoute = VendorOnboardingCompanyRouteImport.update({
  id: '/vendor-onboarding/company',
  path: '/vendor-onboarding/company',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorOnboardingCompleteRoute =
  VendorOnboardingCompleteRouteImport.update({
    id: '/vendor-onboarding/complete',
    path: '/vendor-onboarding/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const VendorOnboardingComplianceRoute =
  VendorOnboardingComplianceRouteImport.update({
    id: '/vendor-onboarding/compliance',
    path: '/vendor-onboarding/compliance',
    getParentRoute: () => rootRouteImport,
  } as any)
const VendorOnboardingProfileRoute = VendorOnboardingProfileRouteImport.update({
  id: '/vendor-onboarding/profile',
  path: '/vendor-onboarding/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorOnboardingReviewRoute = VendorOnboardingReviewRouteImport.update({
  id: '/vendor-onboarding/review',
  path: '/vendor-onboarding/review',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/vendor/',
  path: '/vendor/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorApplicationRoute = VendorApplicationRouteImport.update({
  id: '/vendor/application',
  path: '/vendor/application',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorApplicationsRoute = VendorApplicationsRouteImport.update({
  id: '/vendor/applications',
  path: '/vendor/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDocumentsRoute = VendorDocumentsRouteImport.update({
  id: '/vendor/documents',
  path: '/vendor/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorInquiriesRoute = VendorInquiriesRouteImport.update({
  id: '/vendor/inquiries',
  path: '/vendor/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorLeadsRoute = VendorLeadsRouteImport.update({
  id: '/vendor/leads',
  path: '/vendor/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorMessagesRoute = VendorMessagesRouteImport.update({
  id: '/vendor/messages',
  path: '/vendor/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorNotificationsRoute = VendorNotificationsRouteImport.update({
  id: '/vendor/notifications',
  path: '/vendor/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorOnboardingRoute = VendorOnboardingRouteImport.update({
  id: '/vendor/onboarding',
  path: '/vendor/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorPaymentsRoute = VendorPaymentsRouteImport.update({
  id: '/vendor/payments',
  path: '/vendor/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorPayoutSettingsRoute = VendorPayoutSettingsRouteImport.update({
  id: '/vendor/payout-settings',
  path: '/vendor/payout-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorPayoutsRoute = VendorPayoutsRouteImport.update({
  id: '/vendor/payouts',
  path: '/vendor/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProfileRoute = VendorProfileRouteImport.update({
  id: '/vendor/profile',
  path: '/vendor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProfileShowcaseRoute = VendorProfileShowcaseRouteImport.update({
  id: '/vendor/profile-showcase',
  path: '/vendor/profile-showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorReportsRoute = VendorReportsRouteImport.update({
  id: '/vendor/reports',
  path: '/vendor/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSettingsRoute = VendorSettingsRouteImport.update({
  id: '/vendor/settings',
  path: '/vendor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSubscriptionRoute = VendorSubscriptionRouteImport.update({
  id: '/vendor/subscription',
  path: '/vendor/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsVendorIdRoute = VendorsVendorIdRouteImport.update({
  id: '/vendors/$vendorId',
  path: '/vendors/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRfqIndexRoute = AdminRfqIndexRouteImport.update({
  id: '/admin/rfq/',
  path: '/admin/rfq/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRfqCreateRoute = AdminRfqCreateRouteImport.update({
  id: '/admin/rfq/create',
  path: '/admin/rfq/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRfqCreateDetailedRoute = AdminRfqCreateDetailedRouteImport.update({
  id: '/admin/rfq/create-detailed',
  path: '/admin/rfq/create-detailed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsLabsRoute = AdminSettingsLabsRouteImport.update({
  id: '/admin/settings/labs',
  path: '/admin/settings/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamIndexRoute = AdminTeamIndexRouteImport.update({
  id: '/admin/team/',
  path: '/admin/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamMemberIdRoute = AdminTeamMemberIdRouteImport.update({
  id: '/admin/team/$memberId',
  path: '/admin/team/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsIdRoute = AdminVendorsIdRouteImport.update({
  id: '/admin/vendors/$id',
  path: '/admin/vendors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/dashboard/projects/',
  path: '/dashboard/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsIdRoute = DashboardProjectsIdRouteImport.update({
  id: '/dashboard/projects/$id',
  path: '/dashboard/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorContractsIndexRoute = VendorContractsIndexRouteImport.update({
  id: '/vendor/contracts/',
  path: '/vendor/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorContractsIdRoute = VendorContractsIdRouteImport.update({
  id: '/vendor/contracts/$id',
  path: '/vendor/contracts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProjectsIndexRoute = VendorProjectsIndexRouteImport.update({
  id: '/vendor/projects/',
  path: '/vendor/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProjectsIdRoute = VendorProjectsIdRouteImport.update({
  id: '/vendor/projects/$id',
  path: '/vendor/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRfqIndexRoute = VendorRfqIndexRouteImport.update({
  id: '/vendor/rfq/',
  path: '/vendor/rfq/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRfqDashboardRoute = VendorRfqDashboardRouteImport.update({
  id: '/vendor/rfq/dashboard',
  path: '/vendor/rfq/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRfqsIndexRoute = VendorRfqsIndexRouteImport.update({
  id: '/vendor/rfqs/',
  path: '/vendor/rfqs/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRfqsIdRoute = VendorRfqsIdRouteImport.update({
  id: '/vendor/rfqs/$id',
  path: '/vendor/rfqs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRfqIdIndexRoute = AdminRfqIdIndexRouteImport.update({
  id: '/admin/rfq/$id/',
  path: '/admin/rfq/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRfqIdEditRoute = AdminRfqIdEditRouteImport.update({
  id: '/admin/rfq/$id/edit',
  path: '/admin/rfq/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRfqIdIndexRoute = VendorRfqIdIndexRouteImport.update({
  id: '/vendor/rfq/$id/',
  path: '/vendor/rfq/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRfqIdBidRoute = VendorRfqIdBidRouteImport.update({
  id: '/vendor/rfq/$id/bid',
  path: '/vendor/rfq/$id/bid',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRfqIdDetailsRoute = VendorRfqIdDetailsRouteImport.update({
  id: '/vendor/rfq/$id/details',
  path: '/vendor/rfq/$id/details',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/auth-debug': typeof AuthDebugRoute
  '/auth-test': typeof AuthTestRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/gallery': typeof GalleryRoute
  '/join-as-vendor': typeof JoinAsVendorRoute
  '/login-bridge': typeof LoginBridgeRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/request-quote': typeof RequestQuoteRoute
  '/rfq-system': typeof RfqSystemRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bids': typeof AdminBidsRoute
  '/admin/component-playground': typeof AdminComponentPlaygroundRoute
  '/admin/control-suite': typeof AdminControlSuiteRoute
  '/admin/design-tokens': typeof AdminDesignTokensRoute
  '/admin/emd': typeof AdminEmdRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/rfq-access': typeof AdminRfqAccessRoute
  '/admin/salesiq': typeof AdminSalesiqRoute
  '/admin/security-testing': typeof AdminSecurityTestingRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/testing': typeof AdminTestingRoute
  '/admin/work-orders': typeof AdminWorkOrdersRoute
  '/apartments/$id': typeof ApartmentsIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/blog/how-to-choose-property-management-company': typeof BlogHowToChoosePropertyManagementCompanyRoute
  '/book/$propertyId': typeof BookPropertyIdRoute
  '/booking/$id': typeof BookingIdRoute
  '/dashboard/properties': typeof DashboardPropertiesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/rfq/$id': typeof RfqIdRoute
  '/services/consultation': typeof ServicesConsultationRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/property-management': typeof ServicesPropertyManagementRoute
  '/vendor-onboarding/capabilities': typeof VendorOnboardingCapabilitiesRoute
  '/vendor-onboarding/company': typeof VendorOnboardingCompanyRoute
  '/vendor-onboarding/complete': typeof VendorOnboardingCompleteRoute
  '/vendor-onboarding/compliance': typeof VendorOnboardingComplianceRoute
  '/vendor-onboarding/profile': typeof VendorOnboardingProfileRoute
  '/vendor-onboarding/review': typeof VendorOnboardingReviewRoute
  '/vendor/application': typeof VendorApplicationRoute
  '/vendor/applications': typeof VendorApplicationsRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/documents': typeof VendorDocumentsRoute
  '/vendor/inquiries': typeof VendorInquiriesRoute
  '/vendor/leads': typeof VendorLeadsRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/onboarding': typeof VendorOnboardingRoute
  '/vendor/payments': typeof VendorPaymentsRoute
  '/vendor/payout-settings': typeof VendorPayoutSettingsRoute
  '/vendor/payouts': typeof VendorPayoutsRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/profile-showcase': typeof VendorProfileShowcaseRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/subscription': typeof VendorSubscriptionRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/rfq/': typeof RfqIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/vendor-onboarding/': typeof VendorOnboardingIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/admin/rfq/create': typeof AdminRfqCreateRoute
  '/admin/rfq/create-detailed': typeof AdminRfqCreateDetailedRoute
  '/admin/settings/labs': typeof AdminSettingsLabsRoute
  '/admin/team/$memberId': typeof AdminTeamMemberIdRoute
  '/admin/vendors/$id': typeof AdminVendorsIdRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/vendor/contracts/$id': typeof VendorContractsIdRoute
  '/vendor/projects/$id': typeof VendorProjectsIdRoute
  '/vendor/rfq/dashboard': typeof VendorRfqDashboardRoute
  '/vendor/rfqs/$id': typeof VendorRfqsIdRoute
  '/admin/rfq/': typeof AdminRfqIndexRoute
  '/admin/team/': typeof AdminTeamIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/vendor/contracts/': typeof VendorContractsIndexRoute
  '/vendor/projects/': typeof VendorProjectsIndexRoute
  '/vendor/rfq/': typeof VendorRfqIndexRoute
  '/vendor/rfqs/': typeof VendorRfqsIndexRoute
  '/admin/rfq/$id/edit': typeof AdminRfqIdEditRoute
  '/vendor/rfq/$id/bid': typeof VendorRfqIdBidRoute
  '/vendor/rfq/$id/details': typeof VendorRfqIdDetailsRoute
  '/admin/rfq/$id/': typeof AdminRfqIdIndexRoute
  '/vendor/rfq/$id/': typeof VendorRfqIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/auth-debug': typeof AuthDebugRoute
  '/auth-test': typeof AuthTestRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/gallery': typeof GalleryRoute
  '/join-as-vendor': typeof JoinAsVendorRoute
  '/login-bridge': typeof LoginBridgeRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/request-quote': typeof RequestQuoteRoute
  '/rfq-system': typeof RfqSystemRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bids': typeof AdminBidsRoute
  '/admin/component-playground': typeof AdminComponentPlaygroundRoute
  '/admin/control-suite': typeof AdminControlSuiteRoute
  '/admin/design-tokens': typeof AdminDesignTokensRoute
  '/admin/emd': typeof AdminEmdRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/rfq-access': typeof AdminRfqAccessRoute
  '/admin/salesiq': typeof AdminSalesiqRoute
  '/admin/security-testing': typeof AdminSecurityTestingRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/testing': typeof AdminTestingRoute
  '/admin/work-orders': typeof AdminWorkOrdersRoute
  '/apartments/$id': typeof ApartmentsIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/blog/how-to-choose-property-management-company': typeof BlogHowToChoosePropertyManagementCompanyRoute
  '/book/$propertyId': typeof BookPropertyIdRoute
  '/booking/$id': typeof BookingIdRoute
  '/dashboard/properties': typeof DashboardPropertiesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/rfq/$id': typeof RfqIdRoute
  '/services/consultation': typeof ServicesConsultationRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/property-management': typeof ServicesPropertyManagementRoute
  '/vendor-onboarding/capabilities': typeof VendorOnboardingCapabilitiesRoute
  '/vendor-onboarding/company': typeof VendorOnboardingCompanyRoute
  '/vendor-onboarding/complete': typeof VendorOnboardingCompleteRoute
  '/vendor-onboarding/compliance': typeof VendorOnboardingComplianceRoute
  '/vendor-onboarding/profile': typeof VendorOnboardingProfileRoute
  '/vendor-onboarding/review': typeof VendorOnboardingReviewRoute
  '/vendor/application': typeof VendorApplicationRoute
  '/vendor/applications': typeof VendorApplicationsRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/documents': typeof VendorDocumentsRoute
  '/vendor/inquiries': typeof VendorInquiriesRoute
  '/vendor/leads': typeof VendorLeadsRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/onboarding': typeof VendorOnboardingRoute
  '/vendor/payments': typeof VendorPaymentsRoute
  '/vendor/payout-settings': typeof VendorPayoutSettingsRoute
  '/vendor/payouts': typeof VendorPayoutsRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/profile-showcase': typeof VendorProfileShowcaseRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/subscription': typeof VendorSubscriptionRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/rfq': typeof RfqIndexRoute
  '/services': typeof ServicesIndexRoute
  '/vendor-onboarding': typeof VendorOnboardingIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/admin/rfq/create': typeof AdminRfqCreateRoute
  '/admin/rfq/create-detailed': typeof AdminRfqCreateDetailedRoute
  '/admin/settings/labs': typeof AdminSettingsLabsRoute
  '/admin/team/$memberId': typeof AdminTeamMemberIdRoute
  '/admin/vendors/$id': typeof AdminVendorsIdRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/vendor/contracts/$id': typeof VendorContractsIdRoute
  '/vendor/projects/$id': typeof VendorProjectsIdRoute
  '/vendor/rfq/dashboard': typeof VendorRfqDashboardRoute
  '/vendor/rfqs/$id': typeof VendorRfqsIdRoute
  '/admin/rfq': typeof AdminRfqIndexRoute
  '/admin/team': typeof AdminTeamIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/vendor/contracts': typeof VendorContractsIndexRoute
  '/vendor/projects': typeof VendorProjectsIndexRoute
  '/vendor/rfq': typeof VendorRfqIndexRoute
  '/vendor/rfqs': typeof VendorRfqsIndexRoute
  '/admin/rfq/$id/edit': typeof AdminRfqIdEditRoute
  '/vendor/rfq/$id/bid': typeof VendorRfqIdBidRoute
  '/vendor/rfq/$id/details': typeof VendorRfqIdDetailsRoute
  '/admin/rfq/$id': typeof AdminRfqIdIndexRoute
  '/vendor/rfq/$id': typeof VendorRfqIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/auth-debug': typeof AuthDebugRoute
  '/auth-test': typeof AuthTestRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/gallery': typeof GalleryRoute
  '/join-as-vendor': typeof JoinAsVendorRoute
  '/login-bridge': typeof LoginBridgeRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/request-quote': typeof RequestQuoteRoute
  '/rfq-system': typeof RfqSystemRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bids': typeof AdminBidsRoute
  '/admin/component-playground': typeof AdminComponentPlaygroundRoute
  '/admin/control-suite': typeof AdminControlSuiteRoute
  '/admin/design-tokens': typeof AdminDesignTokensRoute
  '/admin/emd': typeof AdminEmdRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/rfq-access': typeof AdminRfqAccessRoute
  '/admin/salesiq': typeof AdminSalesiqRoute
  '/admin/security-testing': typeof AdminSecurityTestingRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/testing': typeof AdminTestingRoute
  '/admin/work-orders': typeof AdminWorkOrdersRoute
  '/apartments/$id': typeof ApartmentsIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/blog/how-to-choose-property-management-company': typeof BlogHowToChoosePropertyManagementCompanyRoute
  '/book/$propertyId': typeof BookPropertyIdRoute
  '/booking/$id': typeof BookingIdRoute
  '/dashboard/properties': typeof DashboardPropertiesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/rfq/$id': typeof RfqIdRoute
  '/services/consultation': typeof ServicesConsultationRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/property-management': typeof ServicesPropertyManagementRoute
  '/vendor-onboarding/capabilities': typeof VendorOnboardingCapabilitiesRoute
  '/vendor-onboarding/company': typeof VendorOnboardingCompanyRoute
  '/vendor-onboarding/complete': typeof VendorOnboardingCompleteRoute
  '/vendor-onboarding/compliance': typeof VendorOnboardingComplianceRoute
  '/vendor-onboarding/profile': typeof VendorOnboardingProfileRoute
  '/vendor-onboarding/review': typeof VendorOnboardingReviewRoute
  '/vendor/application': typeof VendorApplicationRoute
  '/vendor/applications': typeof VendorApplicationsRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/documents': typeof VendorDocumentsRoute
  '/vendor/inquiries': typeof VendorInquiriesRoute
  '/vendor/leads': typeof VendorLeadsRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/onboarding': typeof VendorOnboardingRoute
  '/vendor/payments': typeof VendorPaymentsRoute
  '/vendor/payout-settings': typeof VendorPayoutSettingsRoute
  '/vendor/payouts': typeof VendorPayoutsRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/profile-showcase': typeof VendorProfileShowcaseRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/subscription': typeof VendorSubscriptionRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/rfq/': typeof RfqIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/vendor-onboarding/': typeof VendorOnboardingIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/admin/rfq/create': typeof AdminRfqCreateRoute
  '/admin/rfq/create-detailed': typeof AdminRfqCreateDetailedRoute
  '/admin/settings/labs': typeof AdminSettingsLabsRoute
  '/admin/team/$memberId': typeof AdminTeamMemberIdRoute
  '/admin/vendors/$id': typeof AdminVendorsIdRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/vendor/contracts/$id': typeof VendorContractsIdRoute
  '/vendor/projects/$id': typeof VendorProjectsIdRoute
  '/vendor/rfq/dashboard': typeof VendorRfqDashboardRoute
  '/vendor/rfqs/$id': typeof VendorRfqsIdRoute
  '/admin/rfq/': typeof AdminRfqIndexRoute
  '/admin/team/': typeof AdminTeamIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/vendor/contracts/': typeof VendorContractsIndexRoute
  '/vendor/projects/': typeof VendorProjectsIndexRoute
  '/vendor/rfq/': typeof VendorRfqIndexRoute
  '/vendor/rfqs/': typeof VendorRfqsIndexRoute
  '/admin/rfq/$id/edit': typeof AdminRfqIdEditRoute
  '/vendor/rfq/$id/bid': typeof VendorRfqIdBidRoute
  '/vendor/rfq/$id/details': typeof VendorRfqIdDetailsRoute
  '/admin/rfq/$id/': typeof AdminRfqIdIndexRoute
  '/vendor/rfq/$id/': typeof VendorRfqIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/amenities'
    | '/auth-debug'
    | '/auth-test'
    | '/bookmarks'
    | '/contact'
    | '/design-system'
    | '/gallery'
    | '/join-as-vendor'
    | '/login-bridge'
    | '/news'
    | '/privacy'
    | '/projects'
    | '/request-quote'
    | '/rfq-system'
    | '/settings'
    | '/sitemap'
    | '/terms'
    | '/theme-preview'
    | '/admin/audit'
    | '/admin/bids'
    | '/admin/component-playground'
    | '/admin/control-suite'
    | '/admin/design-tokens'
    | '/admin/emd'
    | '/admin/invoices'
    | '/admin/operations'
    | '/admin/payouts'
    | '/admin/rfq-access'
    | '/admin/salesiq'
    | '/admin/security-testing'
    | '/admin/tenants'
    | '/admin/testing'
    | '/admin/work-orders'
    | '/apartments/$id'
    | '/auth/callback'
    | '/auth/verify'
    | '/blog/how-to-choose-property-management-company'
    | '/book/$propertyId'
    | '/booking/$id'
    | '/dashboard/properties'
    | '/dashboard/settings'
    | '/dashboard/tenants'
    | '/dashboard/users'
    | '/dashboard/vendors'
    | '/properties/$id'
    | '/rfq/$id'
    | '/services/consultation'
    | '/services/maintenance'
    | '/services/property-management'
    | '/vendor-onboarding/capabilities'
    | '/vendor-onboarding/company'
    | '/vendor-onboarding/complete'
    | '/vendor-onboarding/compliance'
    | '/vendor-onboarding/profile'
    | '/vendor-onboarding/review'
    | '/vendor/application'
    | '/vendor/applications'
    | '/vendor/dashboard'
    | '/vendor/documents'
    | '/vendor/inquiries'
    | '/vendor/leads'
    | '/vendor/messages'
    | '/vendor/notifications'
    | '/vendor/onboarding'
    | '/vendor/payments'
    | '/vendor/payout-settings'
    | '/vendor/payouts'
    | '/vendor/profile'
    | '/vendor/profile-showcase'
    | '/vendor/reports'
    | '/vendor/settings'
    | '/vendor/subscription'
    | '/vendors/$vendorId'
    | '/admin/'
    | '/auth/'
    | '/dashboard/'
    | '/properties/'
    | '/rfq/'
    | '/services/'
    | '/vendor-onboarding/'
    | '/vendor/'
    | '/admin/rfq/create'
    | '/admin/rfq/create-detailed'
    | '/admin/settings/labs'
    | '/admin/team/$memberId'
    | '/admin/vendors/$id'
    | '/dashboard/projects/$id'
    | '/vendor/contracts/$id'
    | '/vendor/projects/$id'
    | '/vendor/rfq/dashboard'
    | '/vendor/rfqs/$id'
    | '/admin/rfq/'
    | '/admin/team/'
    | '/dashboard/projects/'
    | '/vendor/contracts/'
    | '/vendor/projects/'
    | '/vendor/rfq/'
    | '/vendor/rfqs/'
    | '/admin/rfq/$id/edit'
    | '/vendor/rfq/$id/bid'
    | '/vendor/rfq/$id/details'
    | '/admin/rfq/$id/'
    | '/vendor/rfq/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/amenities'
    | '/auth-debug'
    | '/auth-test'
    | '/bookmarks'
    | '/contact'
    | '/design-system'
    | '/gallery'
    | '/join-as-vendor'
    | '/login-bridge'
    | '/news'
    | '/privacy'
    | '/projects'
    | '/request-quote'
    | '/rfq-system'
    | '/settings'
    | '/sitemap'
    | '/terms'
    | '/theme-preview'
    | '/admin/audit'
    | '/admin/bids'
    | '/admin/component-playground'
    | '/admin/control-suite'
    | '/admin/design-tokens'
    | '/admin/emd'
    | '/admin/invoices'
    | '/admin/operations'
    | '/admin/payouts'
    | '/admin/rfq-access'
    | '/admin/salesiq'
    | '/admin/security-testing'
    | '/admin/tenants'
    | '/admin/testing'
    | '/admin/work-orders'
    | '/apartments/$id'
    | '/auth/callback'
    | '/auth/verify'
    | '/blog/how-to-choose-property-management-company'
    | '/book/$propertyId'
    | '/booking/$id'
    | '/dashboard/properties'
    | '/dashboard/settings'
    | '/dashboard/tenants'
    | '/dashboard/users'
    | '/dashboard/vendors'
    | '/properties/$id'
    | '/rfq/$id'
    | '/services/consultation'
    | '/services/maintenance'
    | '/services/property-management'
    | '/vendor-onboarding/capabilities'
    | '/vendor-onboarding/company'
    | '/vendor-onboarding/complete'
    | '/vendor-onboarding/compliance'
    | '/vendor-onboarding/profile'
    | '/vendor-onboarding/review'
    | '/vendor/application'
    | '/vendor/applications'
    | '/vendor/dashboard'
    | '/vendor/documents'
    | '/vendor/inquiries'
    | '/vendor/leads'
    | '/vendor/messages'
    | '/vendor/notifications'
    | '/vendor/onboarding'
    | '/vendor/payments'
    | '/vendor/payout-settings'
    | '/vendor/payouts'
    | '/vendor/profile'
    | '/vendor/profile-showcase'
    | '/vendor/reports'
    | '/vendor/settings'
    | '/vendor/subscription'
    | '/vendors/$vendorId'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/properties'
    | '/rfq'
    | '/services'
    | '/vendor-onboarding'
    | '/vendor'
    | '/admin/rfq/create'
    | '/admin/rfq/create-detailed'
    | '/admin/settings/labs'
    | '/admin/team/$memberId'
    | '/admin/vendors/$id'
    | '/dashboard/projects/$id'
    | '/vendor/contracts/$id'
    | '/vendor/projects/$id'
    | '/vendor/rfq/dashboard'
    | '/vendor/rfqs/$id'
    | '/admin/rfq'
    | '/admin/team'
    | '/dashboard/projects'
    | '/vendor/contracts'
    | '/vendor/projects'
    | '/vendor/rfq'
    | '/vendor/rfqs'
    | '/admin/rfq/$id/edit'
    | '/vendor/rfq/$id/bid'
    | '/vendor/rfq/$id/details'
    | '/admin/rfq/$id'
    | '/vendor/rfq/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/amenities'
    | '/auth-debug'
    | '/auth-test'
    | '/bookmarks'
    | '/contact'
    | '/design-system'
    | '/gallery'
    | '/join-as-vendor'
    | '/login-bridge'
    | '/news'
    | '/privacy'
    | '/projects'
    | '/request-quote'
    | '/rfq-system'
    | '/settings'
    | '/sitemap'
    | '/terms'
    | '/theme-preview'
    | '/admin/audit'
    | '/admin/bids'
    | '/admin/component-playground'
    | '/admin/control-suite'
    | '/admin/design-tokens'
    | '/admin/emd'
    | '/admin/invoices'
    | '/admin/operations'
    | '/admin/payouts'
    | '/admin/rfq-access'
    | '/admin/salesiq'
    | '/admin/security-testing'
    | '/admin/tenants'
    | '/admin/testing'
    | '/admin/work-orders'
    | '/apartments/$id'
    | '/auth/callback'
    | '/auth/verify'
    | '/blog/how-to-choose-property-management-company'
    | '/book/$propertyId'
    | '/booking/$id'
    | '/dashboard/properties'
    | '/dashboard/settings'
    | '/dashboard/tenants'
    | '/dashboard/users'
    | '/dashboard/vendors'
    | '/properties/$id'
    | '/rfq/$id'
    | '/services/consultation'
    | '/services/maintenance'
    | '/services/property-management'
    | '/vendor-onboarding/capabilities'
    | '/vendor-onboarding/company'
    | '/vendor-onboarding/complete'
    | '/vendor-onboarding/compliance'
    | '/vendor-onboarding/profile'
    | '/vendor-onboarding/review'
    | '/vendor/application'
    | '/vendor/applications'
    | '/vendor/dashboard'
    | '/vendor/documents'
    | '/vendor/inquiries'
    | '/vendor/leads'
    | '/vendor/messages'
    | '/vendor/notifications'
    | '/vendor/onboarding'
    | '/vendor/payments'
    | '/vendor/payout-settings'
    | '/vendor/payouts'
    | '/vendor/profile'
    | '/vendor/profile-showcase'
    | '/vendor/reports'
    | '/vendor/settings'
    | '/vendor/subscription'
    | '/vendors/$vendorId'
    | '/admin/'
    | '/auth/'
    | '/dashboard/'
    | '/properties/'
    | '/rfq/'
    | '/services/'
    | '/vendor-onboarding/'
    | '/vendor/'
    | '/admin/rfq/create'
    | '/admin/rfq/create-detailed'
    | '/admin/settings/labs'
    | '/admin/team/$memberId'
    | '/admin/vendors/$id'
    | '/dashboard/projects/$id'
    | '/vendor/contracts/$id'
    | '/vendor/projects/$id'
    | '/vendor/rfq/dashboard'
    | '/vendor/rfqs/$id'
    | '/admin/rfq/'
    | '/admin/team/'
    | '/dashboard/projects/'
    | '/vendor/contracts/'
    | '/vendor/projects/'
    | '/vendor/rfq/'
    | '/vendor/rfqs/'
    | '/admin/rfq/$id/edit'
    | '/vendor/rfq/$id/bid'
    | '/vendor/rfq/$id/details'
    | '/admin/rfq/$id/'
    | '/vendor/rfq/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AmenitiesRoute: typeof AmenitiesRoute
  AuthDebugRoute: typeof AuthDebugRoute
  AuthTestRoute: typeof AuthTestRoute
  BookmarksRoute: typeof BookmarksRoute
  ContactRoute: typeof ContactRoute
  DesignSystemRoute: typeof DesignSystemRoute
  GalleryRoute: typeof GalleryRoute
  JoinAsVendorRoute: typeof JoinAsVendorRoute
  LoginBridgeRoute: typeof LoginBridgeRoute
  NewsRoute: typeof NewsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  RequestQuoteRoute: typeof RequestQuoteRoute
  RfqSystemRoute: typeof RfqSystemRoute
  SettingsRoute: typeof SettingsRoute
  SitemapRoute: typeof SitemapRoute
  TermsRoute: typeof TermsRoute
  ThemePreviewRoute: typeof ThemePreviewRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBidsRoute: typeof AdminBidsRoute
  AdminComponentPlaygroundRoute: typeof AdminComponentPlaygroundRoute
  AdminControlSuiteRoute: typeof AdminControlSuiteRoute
  AdminDesignTokensRoute: typeof AdminDesignTokensRoute
  AdminEmdRoute: typeof AdminEmdRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminRfqAccessRoute: typeof AdminRfqAccessRoute
  AdminSalesiqRoute: typeof AdminSalesiqRoute
  AdminSecurityTestingRoute: typeof AdminSecurityTestingRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminTestingRoute: typeof AdminTestingRoute
  AdminWorkOrdersRoute: typeof AdminWorkOrdersRoute
  ApartmentsIdRoute: typeof ApartmentsIdRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  BlogHowToChoosePropertyManagementCompanyRoute: typeof BlogHowToChoosePropertyManagementCompanyRoute
  BookPropertyIdRoute: typeof BookPropertyIdRoute
  BookingIdRoute: typeof BookingIdRoute
  DashboardPropertiesRoute: typeof DashboardPropertiesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTenantsRoute: typeof DashboardTenantsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardVendorsRoute: typeof DashboardVendorsRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  RfqIdRoute: typeof RfqIdRoute
  ServicesConsultationRoute: typeof ServicesConsultationRoute
  ServicesMaintenanceRoute: typeof ServicesMaintenanceRoute
  ServicesPropertyManagementRoute: typeof ServicesPropertyManagementRoute
  VendorOnboardingCapabilitiesRoute: typeof VendorOnboardingCapabilitiesRoute
  VendorOnboardingCompanyRoute: typeof VendorOnboardingCompanyRoute
  VendorOnboardingCompleteRoute: typeof VendorOnboardingCompleteRoute
  VendorOnboardingComplianceRoute: typeof VendorOnboardingComplianceRoute
  VendorOnboardingProfileRoute: typeof VendorOnboardingProfileRoute
  VendorOnboardingReviewRoute: typeof VendorOnboardingReviewRoute
  VendorApplicationRoute: typeof VendorApplicationRoute
  VendorApplicationsRoute: typeof VendorApplicationsRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorDocumentsRoute: typeof VendorDocumentsRoute
  VendorInquiriesRoute: typeof VendorInquiriesRoute
  VendorLeadsRoute: typeof VendorLeadsRoute
  VendorMessagesRoute: typeof VendorMessagesRoute
  VendorNotificationsRoute: typeof VendorNotificationsRoute
  VendorOnboardingRoute: typeof VendorOnboardingRoute
  VendorPaymentsRoute: typeof VendorPaymentsRoute
  VendorPayoutSettingsRoute: typeof VendorPayoutSettingsRoute
  VendorPayoutsRoute: typeof VendorPayoutsRoute
  VendorProfileRoute: typeof VendorProfileRoute
  VendorProfileShowcaseRoute: typeof VendorProfileShowcaseRoute
  VendorReportsRoute: typeof VendorReportsRoute
  VendorSettingsRoute: typeof VendorSettingsRoute
  VendorSubscriptionRoute: typeof VendorSubscriptionRoute
  VendorsVendorIdRoute: typeof VendorsVendorIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  RfqIndexRoute: typeof RfqIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  VendorOnboardingIndexRoute: typeof VendorOnboardingIndexRoute
  VendorIndexRoute: typeof VendorIndexRoute
  AdminRfqCreateRoute: typeof AdminRfqCreateRoute
  AdminRfqCreateDetailedRoute: typeof AdminRfqCreateDetailedRoute
  AdminSettingsLabsRoute: typeof AdminSettingsLabsRoute
  AdminTeamMemberIdRoute: typeof AdminTeamMemberIdRoute
  AdminVendorsIdRoute: typeof AdminVendorsIdRoute
  DashboardProjectsIdRoute: typeof DashboardProjectsIdRoute
  VendorContractsIdRoute: typeof VendorContractsIdRoute
  VendorProjectsIdRoute: typeof VendorProjectsIdRoute
  VendorRfqDashboardRoute: typeof VendorRfqDashboardRoute
  VendorRfqsIdRoute: typeof VendorRfqsIdRoute
  AdminRfqIndexRoute: typeof AdminRfqIndexRoute
  AdminTeamIndexRoute: typeof AdminTeamIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  VendorContractsIndexRoute: typeof VendorContractsIndexRoute
  VendorProjectsIndexRoute: typeof VendorProjectsIndexRoute
  VendorRfqIndexRoute: typeof VendorRfqIndexRoute
  VendorRfqsIndexRoute: typeof VendorRfqsIndexRoute
  AdminRfqIdEditRoute: typeof AdminRfqIdEditRoute
  VendorRfqIdBidRoute: typeof VendorRfqIdBidRoute
  VendorRfqIdDetailsRoute: typeof VendorRfqIdDetailsRoute
  AdminRfqIdIndexRoute: typeof AdminRfqIdIndexRoute
  VendorRfqIdIndexRoute: typeof VendorRfqIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-debug': {
      id: '/auth-debug'
      path: '/auth-debug'
      fullPath: '/auth-debug'
      preLoaderRoute: typeof AuthDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-test': {
      id: '/auth-test'
      path: '/auth-test'
      fullPath: '/auth-test'
      preLoaderRoute: typeof AuthTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-as-vendor': {
      id: '/join-as-vendor'
      path: '/join-as-vendor'
      fullPath: '/join-as-vendor'
      preLoaderRoute: typeof JoinAsVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-bridge': {
      id: '/login-bridge'
      path: '/login-bridge'
      fullPath: '/login-bridge'
      preLoaderRoute: typeof LoginBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote': {
      id: '/request-quote'
      path: '/request-quote'
      fullPath: '/request-quote'
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq-system': {
      id: '/rfq-system'
      path: '/rfq-system'
      fullPath: '/rfq-system'
      preLoaderRoute: typeof RfqSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme-preview': {
      id: '/theme-preview'
      path: '/theme-preview'
      fullPath: '/theme-preview'
      preLoaderRoute: typeof ThemePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bids': {
      id: '/admin/bids'
      path: '/admin/bids'
      fullPath: '/admin/bids'
      preLoaderRoute: typeof AdminBidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/component-playground': {
      id: '/admin/component-playground'
      path: '/admin/component-playground'
      fullPath: '/admin/component-playground'
      preLoaderRoute: typeof AdminComponentPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/control-suite': {
      id: '/admin/control-suite'
      path: '/admin/control-suite'
      fullPath: '/admin/control-suite'
      preLoaderRoute: typeof AdminControlSuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/design-tokens': {
      id: '/admin/design-tokens'
      path: '/admin/design-tokens'
      fullPath: '/admin/design-tokens'
      preLoaderRoute: typeof AdminDesignTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/emd': {
      id: '/admin/emd'
      path: '/admin/emd'
      fullPath: '/admin/emd'
      preLoaderRoute: typeof AdminEmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/admin/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rfq-access': {
      id: '/admin/rfq-access'
      path: '/admin/rfq-access'
      fullPath: '/admin/rfq-access'
      preLoaderRoute: typeof AdminRfqAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/salesiq': {
      id: '/admin/salesiq'
      path: '/admin/salesiq'
      fullPath: '/admin/salesiq'
      preLoaderRoute: typeof AdminSalesiqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security-testing': {
      id: '/admin/security-testing'
      path: '/admin/security-testing'
      fullPath: '/admin/security-testing'
      preLoaderRoute: typeof AdminSecurityTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testing': {
      id: '/admin/testing'
      path: '/admin/testing'
      fullPath: '/admin/testing'
      preLoaderRoute: typeof AdminTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/work-orders': {
      id: '/admin/work-orders'
      path: '/admin/work-orders'
      fullPath: '/admin/work-orders'
      preLoaderRoute: typeof AdminWorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments/$id': {
      id: '/apartments/$id'
      path: '/apartments/$id'
      fullPath: '/apartments/$id'
      preLoaderRoute: typeof ApartmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-choose-property-management-company': {
      id: '/blog/how-to-choose-property-management-company'
      path: '/blog/how-to-choose-property-management-company'
      fullPath: '/blog/how-to-choose-property-management-company'
      preLoaderRoute: typeof BlogHowToChoosePropertyManagementCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$propertyId': {
      id: '/book/$propertyId'
      path: '/book/$propertyId'
      fullPath: '/book/$propertyId'
      preLoaderRoute: typeof BookPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/properties': {
      id: '/dashboard/properties'
      path: '/dashboard/properties'
      fullPath: '/dashboard/properties'
      preLoaderRoute: typeof DashboardPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tenants': {
      id: '/dashboard/tenants'
      path: '/dashboard/tenants'
      fullPath: '/dashboard/tenants'
      preLoaderRoute: typeof DashboardTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vendors': {
      id: '/dashboard/vendors'
      path: '/dashboard/vendors'
      fullPath: '/dashboard/vendors'
      preLoaderRoute: typeof DashboardVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq/': {
      id: '/rfq/'
      path: '/rfq'
      fullPath: '/rfq/'
      preLoaderRoute: typeof RfqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq/$id': {
      id: '/rfq/$id'
      path: '/rfq/$id'
      fullPath: '/rfq/$id'
      preLoaderRoute: typeof RfqIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/consultation': {
      id: '/services/consultation'
      path: '/services/consultation'
      fullPath: '/services/consultation'
      preLoaderRoute: typeof ServicesConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/maintenance': {
      id: '/services/maintenance'
      path: '/services/maintenance'
      fullPath: '/services/maintenance'
      preLoaderRoute: typeof ServicesMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/property-management': {
      id: '/services/property-management'
      path: '/services/property-management'
      fullPath: '/services/property-management'
      preLoaderRoute: typeof ServicesPropertyManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-onboarding/': {
      id: '/vendor-onboarding/'
      path: '/vendor-onboarding'
      fullPath: '/vendor-onboarding/'
      preLoaderRoute: typeof VendorOnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-onboarding/capabilities': {
      id: '/vendor-onboarding/capabilities'
      path: '/vendor-onboarding/capabilities'
      fullPath: '/vendor-onboarding/capabilities'
      preLoaderRoute: typeof VendorOnboardingCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-onboarding/company': {
      id: '/vendor-onboarding/company'
      path: '/vendor-onboarding/company'
      fullPath: '/vendor-onboarding/company'
      preLoaderRoute: typeof VendorOnboardingCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-onboarding/complete': {
      id: '/vendor-onboarding/complete'
      path: '/vendor-onboarding/complete'
      fullPath: '/vendor-onboarding/complete'
      preLoaderRoute: typeof VendorOnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-onboarding/compliance': {
      id: '/vendor-onboarding/compliance'
      path: '/vendor-onboarding/compliance'
      fullPath: '/vendor-onboarding/compliance'
      preLoaderRoute: typeof VendorOnboardingComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-onboarding/profile': {
      id: '/vendor-onboarding/profile'
      path: '/vendor-onboarding/profile'
      fullPath: '/vendor-onboarding/profile'
      preLoaderRoute: typeof VendorOnboardingProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-onboarding/review': {
      id: '/vendor-onboarding/review'
      path: '/vendor-onboarding/review'
      fullPath: '/vendor-onboarding/review'
      preLoaderRoute: typeof VendorOnboardingReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/vendor'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/application': {
      id: '/vendor/application'
      path: '/vendor/application'
      fullPath: '/vendor/application'
      preLoaderRoute: typeof VendorApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/applications': {
      id: '/vendor/applications'
      path: '/vendor/applications'
      fullPath: '/vendor/applications'
      preLoaderRoute: typeof VendorApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/documents': {
      id: '/vendor/documents'
      path: '/vendor/documents'
      fullPath: '/vendor/documents'
      preLoaderRoute: typeof VendorDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/inquiries': {
      id: '/vendor/inquiries'
      path: '/vendor/inquiries'
      fullPath: '/vendor/inquiries'
      preLoaderRoute: typeof VendorInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/leads': {
      id: '/vendor/leads'
      path: '/vendor/leads'
      fullPath: '/vendor/leads'
      preLoaderRoute: typeof VendorLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/messages': {
      id: '/vendor/messages'
      path: '/vendor/messages'
      fullPath: '/vendor/messages'
      preLoaderRoute: typeof VendorMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/notifications': {
      id: '/vendor/notifications'
      path: '/vendor/notifications'
      fullPath: '/vendor/notifications'
      preLoaderRoute: typeof VendorNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/onboarding': {
      id: '/vendor/onboarding'
      path: '/vendor/onboarding'
      fullPath: '/vendor/onboarding'
      preLoaderRoute: typeof VendorOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/payments': {
      id: '/vendor/payments'
      path: '/vendor/payments'
      fullPath: '/vendor/payments'
      preLoaderRoute: typeof VendorPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/payout-settings': {
      id: '/vendor/payout-settings'
      path: '/vendor/payout-settings'
      fullPath: '/vendor/payout-settings'
      preLoaderRoute: typeof VendorPayoutSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/payouts': {
      id: '/vendor/payouts'
      path: '/vendor/payouts'
      fullPath: '/vendor/payouts'
      preLoaderRoute: typeof VendorPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/profile': {
      id: '/vendor/profile'
      path: '/vendor/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof VendorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/profile-showcase': {
      id: '/vendor/profile-showcase'
      path: '/vendor/profile-showcase'
      fullPath: '/vendor/profile-showcase'
      preLoaderRoute: typeof VendorProfileShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/reports': {
      id: '/vendor/reports'
      path: '/vendor/reports'
      fullPath: '/vendor/reports'
      preLoaderRoute: typeof VendorReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/settings': {
      id: '/vendor/settings'
      path: '/vendor/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/subscription': {
      id: '/vendor/subscription'
      path: '/vendor/subscription'
      fullPath: '/vendor/subscription'
      preLoaderRoute: typeof VendorSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$vendorId': {
      id: '/vendors/$vendorId'
      path: '/vendors/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof VendorsVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rfq/': {
      id: '/admin/rfq/'
      path: '/admin/rfq'
      fullPath: '/admin/rfq/'
      preLoaderRoute: typeof AdminRfqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rfq/create': {
      id: '/admin/rfq/create'
      path: '/admin/rfq/create'
      fullPath: '/admin/rfq/create'
      preLoaderRoute: typeof AdminRfqCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rfq/create-detailed': {
      id: '/admin/rfq/create-detailed'
      path: '/admin/rfq/create-detailed'
      fullPath: '/admin/rfq/create-detailed'
      preLoaderRoute: typeof AdminRfqCreateDetailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/labs': {
      id: '/admin/settings/labs'
      path: '/admin/settings/labs'
      fullPath: '/admin/settings/labs'
      preLoaderRoute: typeof AdminSettingsLabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team/': {
      id: '/admin/team/'
      path: '/admin/team'
      fullPath: '/admin/team/'
      preLoaderRoute: typeof AdminTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team/$memberId': {
      id: '/admin/team/$memberId'
      path: '/admin/team/$memberId'
      fullPath: '/admin/team/$memberId'
      preLoaderRoute: typeof AdminTeamMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors/$id': {
      id: '/admin/vendors/$id'
      path: '/admin/vendors/$id'
      fullPath: '/admin/vendors/$id'
      preLoaderRoute: typeof AdminVendorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/dashboard/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/$id': {
      id: '/dashboard/projects/$id'
      path: '/dashboard/projects/$id'
      fullPath: '/dashboard/projects/$id'
      preLoaderRoute: typeof DashboardProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/contracts/': {
      id: '/vendor/contracts/'
      path: '/vendor/contracts'
      fullPath: '/vendor/contracts/'
      preLoaderRoute: typeof VendorContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/contracts/$id': {
      id: '/vendor/contracts/$id'
      path: '/vendor/contracts/$id'
      fullPath: '/vendor/contracts/$id'
      preLoaderRoute: typeof VendorContractsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/projects/': {
      id: '/vendor/projects/'
      path: '/vendor/projects'
      fullPath: '/vendor/projects/'
      preLoaderRoute: typeof VendorProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/projects/$id': {
      id: '/vendor/projects/$id'
      path: '/vendor/projects/$id'
      fullPath: '/vendor/projects/$id'
      preLoaderRoute: typeof VendorProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/rfq/': {
      id: '/vendor/rfq/'
      path: '/vendor/rfq'
      fullPath: '/vendor/rfq/'
      preLoaderRoute: typeof VendorRfqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/rfq/dashboard': {
      id: '/vendor/rfq/dashboard'
      path: '/vendor/rfq/dashboard'
      fullPath: '/vendor/rfq/dashboard'
      preLoaderRoute: typeof VendorRfqDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/rfqs/': {
      id: '/vendor/rfqs/'
      path: '/vendor/rfqs'
      fullPath: '/vendor/rfqs/'
      preLoaderRoute: typeof VendorRfqsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/rfqs/$id': {
      id: '/vendor/rfqs/$id'
      path: '/vendor/rfqs/$id'
      fullPath: '/vendor/rfqs/$id'
      preLoaderRoute: typeof VendorRfqsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rfq/$id/': {
      id: '/admin/rfq/$id/'
      path: '/admin/rfq/$id'
      fullPath: '/admin/rfq/$id/'
      preLoaderRoute: typeof AdminRfqIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rfq/$id/edit': {
      id: '/admin/rfq/$id/edit'
      path: '/admin/rfq/$id/edit'
      fullPath: '/admin/rfq/$id/edit'
      preLoaderRoute: typeof AdminRfqIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/rfq/$id/': {
      id: '/vendor/rfq/$id/'
      path: '/vendor/rfq/$id'
      fullPath: '/vendor/rfq/$id/'
      preLoaderRoute: typeof VendorRfqIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/rfq/$id/bid': {
      id: '/vendor/rfq/$id/bid'
      path: '/vendor/rfq/$id/bid'
      fullPath: '/vendor/rfq/$id/bid'
      preLoaderRoute: typeof VendorRfqIdBidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/rfq/$id/details': {
      id: '/vendor/rfq/$id/details'
      path: '/vendor/rfq/$id/details'
      fullPath: '/vendor/rfq/$id/details'
      preLoaderRoute: typeof VendorRfqIdDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AmenitiesRoute: AmenitiesRoute,
  AuthDebugRoute: AuthDebugRoute,
  AuthTestRoute: AuthTestRoute,
  BookmarksRoute: BookmarksRoute,
  ContactRoute: ContactRoute,
  DesignSystemRoute: DesignSystemRoute,
  GalleryRoute: GalleryRoute,
  JoinAsVendorRoute: JoinAsVendorRoute,
  LoginBridgeRoute: LoginBridgeRoute,
  NewsRoute: NewsRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  RequestQuoteRoute: RequestQuoteRoute,
  RfqSystemRoute: RfqSystemRoute,
  SettingsRoute: SettingsRoute,
  SitemapRoute: SitemapRoute,
  TermsRoute: TermsRoute,
  ThemePreviewRoute: ThemePreviewRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBidsRoute: AdminBidsRoute,
  AdminComponentPlaygroundRoute: AdminComponentPlaygroundRoute,
  AdminControlSuiteRoute: AdminControlSuiteRoute,
  AdminDesignTokensRoute: AdminDesignTokensRoute,
  AdminEmdRoute: AdminEmdRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminRfqAccessRoute: AdminRfqAccessRoute,
  AdminSalesiqRoute: AdminSalesiqRoute,
  AdminSecurityTestingRoute: AdminSecurityTestingRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminTestingRoute: AdminTestingRoute,
  AdminWorkOrdersRoute: AdminWorkOrdersRoute,
  ApartmentsIdRoute: ApartmentsIdRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  BlogHowToChoosePropertyManagementCompanyRoute:
    BlogHowToChoosePropertyManagementCompanyRoute,
  BookPropertyIdRoute: BookPropertyIdRoute,
  BookingIdRoute: BookingIdRoute,
  DashboardPropertiesRoute: DashboardPropertiesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTenantsRoute: DashboardTenantsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardVendorsRoute: DashboardVendorsRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  RfqIdRoute: RfqIdRoute,
  ServicesConsultationRoute: ServicesConsultationRoute,
  ServicesMaintenanceRoute: ServicesMaintenanceRoute,
  ServicesPropertyManagementRoute: ServicesPropertyManagementRoute,
  VendorOnboardingCapabilitiesRoute: VendorOnboardingCapabilitiesRoute,
  VendorOnboardingCompanyRoute: VendorOnboardingCompanyRoute,
  VendorOnboardingCompleteRoute: VendorOnboardingCompleteRoute,
  VendorOnboardingComplianceRoute: VendorOnboardingComplianceRoute,
  VendorOnboardingProfileRoute: VendorOnboardingProfileRoute,
  VendorOnboardingReviewRoute: VendorOnboardingReviewRoute,
  VendorApplicationRoute: VendorApplicationRoute,
  VendorApplicationsRoute: VendorApplicationsRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorDocumentsRoute: VendorDocumentsRoute,
  VendorInquiriesRoute: VendorInquiriesRoute,
  VendorLeadsRoute: VendorLeadsRoute,
  VendorMessagesRoute: VendorMessagesRoute,
  VendorNotificationsRoute: VendorNotificationsRoute,
  VendorOnboardingRoute: VendorOnboardingRoute,
  VendorPaymentsRoute: VendorPaymentsRoute,
  VendorPayoutSettingsRoute: VendorPayoutSettingsRoute,
  VendorPayoutsRoute: VendorPayoutsRoute,
  VendorProfileRoute: VendorProfileRoute,
  VendorProfileShowcaseRoute: VendorProfileShowcaseRoute,
  VendorReportsRoute: VendorReportsRoute,
  VendorSettingsRoute: VendorSettingsRoute,
  VendorSubscriptionRoute: VendorSubscriptionRoute,
  VendorsVendorIdRoute: VendorsVendorIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  RfqIndexRoute: RfqIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  VendorOnboardingIndexRoute: VendorOnboardingIndexRoute,
  VendorIndexRoute: VendorIndexRoute,
  AdminRfqCreateRoute: AdminRfqCreateRoute,
  AdminRfqCreateDetailedRoute: AdminRfqCreateDetailedRoute,
  AdminSettingsLabsRoute: AdminSettingsLabsRoute,
  AdminTeamMemberIdRoute: AdminTeamMemberIdRoute,
  AdminVendorsIdRoute: AdminVendorsIdRoute,
  DashboardProjectsIdRoute: DashboardProjectsIdRoute,
  VendorContractsIdRoute: VendorContractsIdRoute,
  VendorProjectsIdRoute: VendorProjectsIdRoute,
  VendorRfqDashboardRoute: VendorRfqDashboardRoute,
  VendorRfqsIdRoute: VendorRfqsIdRoute,
  AdminRfqIndexRoute: AdminRfqIndexRoute,
  AdminTeamIndexRoute: AdminTeamIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  VendorContractsIndexRoute: VendorContractsIndexRoute,
  VendorProjectsIndexRoute: VendorProjectsIndexRoute,
  VendorRfqIndexRoute: VendorRfqIndexRoute,
  VendorRfqsIndexRoute: VendorRfqsIndexRoute,
  AdminRfqIdEditRoute: AdminRfqIdEditRoute,
  VendorRfqIdBidRoute: VendorRfqIdBidRoute,
  VendorRfqIdDetailsRoute: VendorRfqIdDetailsRoute,
  AdminRfqIdIndexRoute: AdminRfqIdIndexRoute,
  VendorRfqIdIndexRoute: VendorRfqIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
