
-- Fix property creation: identity column must use GENERATED BY DEFAULT
ALTER TABLE properties ALTER COLUMN id SET GENERATED BY DEFAULT;

-- Junction table: RFQ ↔ Properties with service types
CREATE TABLE IF NOT EXISTS public.rfq_properties (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  rfq_id uuid NOT NULL REFERENCES rfqs(id) ON DELETE CASCADE,
  property_id bigint NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  service_types text[] NOT NULL DEFAULT '{}',
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(rfq_id, property_id)
);

ALTER TABLE rfq_properties ENABLE ROW LEVEL SECURITY;

CREATE POLICY "rfq_properties_select" ON rfq_properties FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM rfqs WHERE rfqs.id = rfq_properties.rfq_id AND (
    rfqs.created_by = auth.uid() OR public.is_admin_user(auth.uid())
  )));

CREATE POLICY "rfq_properties_insert" ON rfq_properties FOR INSERT TO authenticated
  WITH CHECK (public.is_admin_user(auth.uid()) OR EXISTS (
    SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'property_manager'
  ));

CREATE POLICY "rfq_properties_update" ON rfq_properties FOR UPDATE TO authenticated
  USING (public.is_admin_user(auth.uid()));

CREATE POLICY "rfq_properties_delete" ON rfq_properties FOR DELETE TO authenticated
  USING (public.is_admin_user(auth.uid()));

CREATE INDEX IF NOT EXISTS idx_rfq_properties_rfq_id ON rfq_properties(rfq_id);
CREATE INDEX IF NOT EXISTS idx_rfq_properties_property_id ON rfq_properties(property_id);
